### ISSUE TITLE
How to use with freemarker

### ISSUE THREAD

**Issue by jaune162** [bclozel/spring-resource-handling#16]
How to use with freemarker?It is supported?

**Comment by bclozel** [comment]
Yes, you can do the same with Freemarker.

You just need to register a `ResourceUrlEncodingFilter` (it's done automatically by Spring Boot) and in your templates, use the `relativeUrl` macro that rewrites the URL (check out [spring.ftl macros](https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/resources/org/springframework/web/servlet/view/freemarker/spring.ftl)).
