### ISSUE TITLE
StringIndexOutOfBoundsException after setting a contextPath

### ISSUE THREAD

**Issue by aberasarte** [bclozel/spring-resource-handling#8]
Hi,
I've downloaded the project to test the ResourceUrlEncodingFilter and it works as expected, however, if I set a Server Context Path in the application.yml, I'm getting a java.lang.StringIndexOutOfBoundsException. This is happening when I'm trying to render an empty url with some params. An example for this scenario could be when you want to render an URL that changes the current locale using the [LocaleChangeInterceptor] (http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/i18n/LocaleChangeInterceptor.html) and render the same page again. 

[I've forked this project] (https://github.com/aberasarte/spring-resource-handling) and reproduced the problem in the [hellojsp] (https://github.com/aberasarte/spring-resource-handling/blob/master/server/src/main/webapp/WEB-INF/jsp/hellojsp.jsp#L22-24) view. Is this an issue or am I missing something?

Thanks,

**Comment by bclozel** [comment]
Thanks @aberasarte ! I've opened an issue for this: [SPR-13018](https://jira.spring.io/browse/SPR-13018).
